#!/bin/sh

MACADDR=$(ip link | grep wlan0: -A 1 | tail -n 1 | awk '{gsub(/:/,""); print tolower($2)}')
WIFISSID="photonicat-${MACADDR:4:8}"

uci set wireless.radio0.disabled=0
uci set wireless.default_radio0.ssid=${WIFISSID}
uci set wireless.radio0.channel=10
uci set wireless.radio0.band=2g
uci set wireless.radio0.htmode=HT20
uci set wireless.default_radio0.network=lan
uci set wireless.default_radio0.mode=ap
uci set wireless.default_radio0.encryption=psk2
uci set wireless.default_radio0.key=photonicat
uci set wireless.default_raido0.wps_pushbutton=0

uci commit
wifi

sleep 3

rm -f /etc/rc.local.d/99firstboot
